if(BUILD_WITH_CUDA)
    find_package(CUDA 12.0)
    if(CUDA_FOUND)
        enable_language(CUDA)
        set(CMAKE_CUDA_STANDARD 20)
        if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
            if(CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "aarch64")
                message(STATUS "Platform: Jetson Orin detected with CUDA")
                set(CUDA_ARCHITECTURES "87")
                add_compile_definitions(PLATFORM_JETSON_ORIN)
                set(BUILD_WITH_TENSORRT ON) # Automatically enable TensorRT for Jetson
            else()
                message(STATUS "Platform: PC Linux x86 with CUDA")
                add_compile_definitions(PLATFORM_PC_X86)
            endif()
        endif()
    else()
        message(WARNING "BUILD_WITH_CUDA is ON, but CUDA 12.0 was not found. Proceeding with CPU-only build.")
        set(BUILD_WITH_CUDA OFF)
        message(STATUS "Platform: PC Linux x86 (CPU only)")
        add_compile_definitions(PLATFORM_PC_X86)
    endif()
else()
    message(STATUS "Platform: PC Linux x86 (CPU only)")
    add_compile_definitions(PLATFORM_PC_X86)
endif()